name: LeighAnn
favicon: null
layout_spectrum: 0.15144
typography_spectrum: 0.99902
title: LeighAnn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7deee'
    - '#000808'
    - '#b59400'
    - '#4292a2'
    - '#706a00'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
